name: LUchem
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.7
    - numpy
    - scipy
    - sympy
    - ipywidgets
    - matplotlib
    - notebook
    - jupyterlab
    - widgetsnbextension
    - faunus=2.4.0
