name: LUchem
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.7
    - numpy
    - scipy
    - sympy
    - ipywidgets>=7
    - matplotlib
    - notebook
    - jupyter
    - nglview
    - mdtraj
    - nodejs>=10
    - widgetsnbextension
    - faunus=2.4.0
    - pip
    - pip:
      - freesasa
